// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD43o0hB7KGEs0PuMmyoSUjYMduyNUzf-8',
    appId: '1:399742150582:android:870471868a282936264317',
    messagingSenderId: '399742150582',
    projectId: 'ichat-ce73a',
    storageBucket: 'ichat-ce73a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEvk7Iitqz39AmjnwvBTe6m1RRZikXfuw',
    appId: '1:399742150582:ios:b453a311138edd5f264317',
    messagingSenderId: '399742150582',
    projectId: 'ichat-ce73a',
    storageBucket: 'ichat-ce73a.appspot.com',
    androidClientId: '399742150582-e505m099blnra3kdkqvc74200kjhl69q.apps.googleusercontent.com',
    iosClientId: '399742150582-tirmki8v83gnmvm2ggq2jjujed44l182.apps.googleusercontent.com',
    iosBundleId: 'com.example.ichat',
  );
}
